[project]
name = "nonebot-plugin-picstatus"
version = "0.5.4"
description = "A NoneBot2 plugin generates a picture which shows the status of current device"
authors = [{ name = "student_2333", email = "lgc2333@126.com" }]
dependencies = [
    "nonebot2>=2.1.2",
    "nonebot-plugin-send-anything-anywhere>=0.4.0",
    "Pillow>=10.1.0",
    "psutil>=5.9.6",
    "anyio>=3.7.1",
    "httpx>=0.25.1",
    "pil-utils>=0.1.8",
]
requires-python = ">=3.8,<4.0"
readme = "README.md"
license = { text = "MIT" }

[project.urls]
homepage = "https://github.com/lgc-NB2Dev/nonebot-plugin-picstatus"

[tool.pdm]
[tool.pdm.dev-dependencies]
dev = []

[tool.pdm.build]
includes = []

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
