[tool.poetry]
name = "nonebot-plugin-picstatus"
version = "0.1.0"
description = "A NoneBot2 plugin generates a picture which shows the status of current device"
authors = ["student_2333 <lgc2333@126.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"
Pillow = "^9.2.0"
psutil = "^5.9.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
